/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.view;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import javax.swing.JButton;
import view.tools.Constants;

/**+
 *
 * @author Doherty
 */
public class InventoryViewport extends Viewport {
    
    public static InventoryViewport inventoryViewport = new InventoryViewport();
    /**
     * Creates new form InventoryViewport
     */
    public InventoryViewport() {
        initComponents();
        this.setPreferredSize(new Dimension(Constants.VIEW_WIDTH, Constants.VIEW_HEIGHT));
        
        int buttonWidth = inventoryPanel.getWidth() / 5;
        int buttonHeight = inventoryPanel.getHeight() / 10;
        for (int i = 0; ++i < 5;) {
            JButton newButton = new JButton();
            newButton.setOpaque(false);
            newButton.setPreferredSize(new Dimension(buttonWidth, buttonHeight));
            newButton.setToolTipText("Click to Equip");
            //newButton.setIcon();
            inventoryPanel.getLayout().addLayoutComponent("itemButton", newButton);
        }
    } 
    
    @Override
    public void visit(ViewportStack viewportStack) {
        ViewportStack.add(inventoryViewport);
    }
    
    public static InventoryViewport getInstance() {
        return inventoryViewport;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        equippedInventoryPanel = new javax.swing.JPanel();
        simpleStatsPanel = new javax.swing.JPanel();
        inventoryPanel = new javax.swing.JPanel();

        setPreferredSize(new Dimension(Constants.GAME_VIEW_WIDTH, Constants.GAME_VIEW_HEIGHT));

        equippedInventoryPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 2, 2, 4, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout equippedInventoryPanelLayout = new javax.swing.GroupLayout(equippedInventoryPanel);
        equippedInventoryPanel.setLayout(equippedInventoryPanelLayout);
        equippedInventoryPanelLayout.setHorizontalGroup(
            equippedInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );
        equippedInventoryPanelLayout.setVerticalGroup(
            equippedInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        simpleStatsPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 4, 4, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout simpleStatsPanelLayout = new javax.swing.GroupLayout(simpleStatsPanel);
        simpleStatsPanel.setLayout(simpleStatsPanelLayout);
        simpleStatsPanelLayout.setHorizontalGroup(
            simpleStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );
        simpleStatsPanelLayout.setVerticalGroup(
            simpleStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        inventoryPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 2, new java.awt.Color(0, 0, 0)));
        inventoryPanel.setPreferredSize(new java.awt.Dimension(400, 600));
        inventoryPanel.setLayout(new java.awt.GridLayout(10, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(inventoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(equippedInventoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpleStatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(equippedInventoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(simpleStatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(inventoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel equippedInventoryPanel;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JPanel simpleStatsPanel;
    // End of variables declaration//GEN-END:variables

}
